C
C(2) THE FOLLOWING DUMMY ROUTINES ARE INCLUDED
C    SIMPLY TO SATISFY EXTERNAL REFERENCES IN SOLID
C
      FUNCTION ZED(M,N)
      ZED = 0.0
      RETURN
      END
C
      FUNCTION ZEDX(M,N)
      ZEDX = 0.0
      RETURN
      END
C
      FUNCTION ZEDY(M,N)
      ZEDY = 0.0
      RETURN
      END
